apiVersion: v1
kind: Pod
metadata:
  name: vgpu-demo
spec:
  schedulerName: vgpu-scheduler
  restartPolicy: OnFailure
  containers:
  - image: nvidia/cuda:9.0-base
    name: pod-ctr
    command: ["sleep"]
    args: ["100000"]

    resources:
      limits:
        vmware.com/vgpu: 1
